### ISSUE TITLE
一加五8.1 启动后List<MusicBean> 报空

### ISSUE THREAD

**Issue by Zenggangyang** [1900Star/SmartisanMusicPlayer#2]

**Comment by 1900Star** [comment]
如果是App运行崩溃的话：会在手机的根目录生成一个名为 CrashLog的文件夹，文件夹里有崩溃日志creash.txt文件，你如果有时间可以把日志发到我的邮箱 www.strangermy98@gmail.com ，这样我可以快速修复Bug。感谢！

**Comment by 1900Star** [comment]
问题已经做了处理，目前项目已经集成了百度统计，所有的Bug和异常我都可以看到。

**Comment by 1900Star** [comment]
问题已经做了处理，目前项目已经集成了百度统计，所有的Bug和异常我都可以看到。
